config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users
  get 'display' => 'displays#show'
  scope '(:locale)', locale: /fr|en/ do

    get 'home' => 'pages#home'
    get 'select_topic' => 'pages#select_topic'
    get 'thank_you' => 'pages#thank_you'
    resources :contents, only: [:new, :create, :index]
    resources :explanations, only: [:new, :create]
    root 'pages#home'

    # Example of regular route:
    #   get 'products/:id' => 'catalog#view'

    # Example of named route that can be invoked with purchase_url(id: product.id)
    #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

    # Example resource route (maps HTTP verbs to controller actions automatically):
    #   resources :products

    # Example resource route with options:
    #   resources :products do
    #     member do
    #       get 'short'
    #       post 'toggle'
    #     end
    #
    #     collection do
    #       get 'sold'
    #     end
    #   end

    # Example resource route with sub-resources:
    #   resources :products do
    #     resources :comments, :sales
    #     resource :seller
    #   end

    # Example resource route with more complex sub-resources:
    #   resources :products do
    #     resources :comments
    #     resources :sales do
    #       get 'recent', on: :collection
    #     end
    #   end

    # Example resource route with concerns:
    #   concern :toggleable do
    #     post 'toggle'
    #   end
    #   resources :posts, concerns: :toggleable
    #   resources :photos, concerns: :toggleable

    # Example resource route within a namespace:
    #   namespace :admin do
    #     # Directs /admin/products/* to Admin::ProductsController
    #     # (app/controllers/admin/products_controller.rb)
    #     resources :products
    #   end
  end
end

app/models/content.rb
# == Schema Information
#
# Table name: contents
#
#  id                   :integer          not null, primary key
#  comment              :string
#  order                :integer
#  category             :string
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  picture_file_name    :string
#  picture_content_type :string
#  picture_file_size    :integer
#  picture_updated_at   :datetime
#

class Content < ActiveRecord::Base
  validates :picture, presence: true
  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/
end

app/models/display.rb
# == Schema Information
#
# Table name: displays
#
#  id              :integer          not null, primary key
#  category        :string
#  last_content_id :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Display < ActiveRecord::Base
end

app/models/explanation.rb
# == Schema Information
#
# Table name: explanations
#
#  id                   :integer          not null, primary key
#  text                 :string
#  category             :string
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  picture_file_name    :string
#  picture_content_type :string
#  picture_file_size    :integer
#  picture_updated_at   :datetime
#

class Explanation < ActiveRecord::Base
  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    { locale: I18n.locale == I18n.default_locale ? nil : I18n.locale }
  end

end

app/controllers/content_controller.rb
class ContentController < ApplicationController
  def new
    @category = params[:category]
  end

  def create
  end

  def index
  end

  private

  def content_params
     params.require(:content).permit(:comment, :category, :picture)
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  def new
    @category = params[:category]
    @content = Content.new

  end

  def create
    @content = Content.new(content_params)
    if @content.save
      redirect_to thank_you_path
    else
      @alert = "Please upload a picture"
      render :new
    end
  end

  def index
  end

  private

  def content_params
     params.require(:content).permit(:comment, :category, :picture)
  end
end

app/controllers/displays_controller.rb
class DisplaysController < ApplicationController

  def show
    display = Display.where(category: params[:category]).first
    p params[:actual_slide]
    @selected_slide = display.last_content_id < Content.last.id ? Content.last.id : params[:actual_slide]
    @category = params[:category]
    @contents = Content.all.where(category: @category)
    @explanation = Explanation.all.where(category: @category).sample
    display.update(last_content_id: Content.last.id)
    render layout: "display"
  end

end

app/controllers/explanations_controller.rb
class ExplanationsController < ApplicationController
  def new
  end

  def create
    @explanation = Explanation.new(explanation_params)
    @explanation.save
    redirect_to thank_you_path
  end

  def index
  end

  private

  def explanation_params
     params.require(:explanation).permit(:text, :category, :picture)
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController

  def home
    render file: "public/home.html.slim", layout: false
  end

  def select_topic
    render file: "public/select_topic.html.slim"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    render file: "public/home.html.slim"
  end

  def select_topic
    render file: "public/select_topic.html.slim"
  end

  def thank_you
    render file: "public/thank_you.html.slim"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/content_helper.rb
module ContentHelper
end

app/helpers/displays_helper.rb
module DisplaysHelper
end

app/views/contents/index.html.slim
h1 Content#index
p Find me in app/views/content/index.html.slim

app/views/contents/new.html.slim
nav.navbar.navbar-fixed-top
  div.navbar-container
    div.navbar-header
      ul.list-inline
        li= link_to :back do
          i.mdi-hardware-keyboard-arrow-left
        li.text-center UPLOAD YOUR PICTURE
.form-container#form-content
  = form_for(@content) do |f|
    = f.hidden_field :category, value: @category
    div.field
      = f.label :picture,"Select a picture from your gallery:",  class: "form-control"
      = f.file_field :picture, class: "form-control"
    br
    div.field
      = f.label :comment,"Add a comment if you wish:",  class: "form-control"
      = f.text_field :comment, placeholder: "Eg. My family eating ice cream!",  class: "form-control"
    div.actions
      = f.submit "Upload", class: "btn btn-flash"

app/views/displays/show.html.slim
#header
  h1.text-center= "UPLOAD A PIC THAT REMINDS YOU OF #{@category.upcase} ON"
  h2.text-center= "flash-forward.herokuapp.com"

#sidebar.text-center
  h1 FUN FACTS
  h1#facts= @explanation.text
    .text-center= image_tag explanation.picture.url(:medium) if explanation.picture_file_name
#slider data-actual-slide="#{@selected_slide}"
  .swiper-container
    .swiper-wrapper
      - @contents.each do |content|
        .swiper-slide
           .content
              = image_tag content.picture.url

           - if content.comment != ""
              #comment
                 p= content.comment
.swiper-button-prev
 .fa-arrow-right= image_tag "swipe.png"
= link_to( display_path, category: @category, )

javascript:
  var actualSlide = $('#slider').attr("data-actual-slide")
  var mySwiper = new Swiper('.swiper-container', {
    speed: 200,
    spaceBetween: 0,
    autoplay: 10000,
    centeredSlides: true,
    touchEventsTarget: "container",
    initialSlide: actualSlide,
    loop: true
  });
  var actualSlide =
  setInterval(function(){
    // var actualSlide = $('#slider').attr("data-actual-slide", mySwiper.activeIndex )
    var initialPage = location.pathname;
    console.log( mySwiper.activeIndex - 1 )
    if( !isNaN(mySwiper.activeIndex) ){
      addOrUpdateUrlParam("actual_slide", mySwiper.activeIndex - 1)
    }
  }, 20000);
  console.log(actualSlide);

  function addOrUpdateUrlParam(name, value){
    var href = window.location.href;
    var regex = new RegExp("[&\\?]" + name + "=");
    if(regex.test(href))
    {
      regex = new RegExp("([&\\?])" + name + "=\\d+");
      window.location.href = href.replace(regex, "$1" + name + "=" + value);
    }
    else
    {
      if(href.indexOf("?") > -1)
        window.location.href = href + "&" + name + "=" + value;
      else
        window.location.href = href + "?" + name + "=" + value;
    }
  }

app/views/explanations/new.html.slim
div.navbar-text
  p New Explanation

.form-container
  = form_for(Explanation.new) do |f|
    div.field
      = f.label :category, class:"form-control"
      br
      = f.select :category, options_for_select([["Select One", ""], "family", "food"])
    div.field
      = f.label :picture
      br
      = f.file_field :picture
    div.field
      = f.label :text
      br
      = f.text_field :text
    div.actions
      = f.submit

app/views/layouts/application.html.slim
doctype html
html
  head
    title Flash Forward
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = stylesheet_link_tag    "application", media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    = yield

app/views/layouts/display.html.slim
doctype html
html
  head
    title Flash Forward
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = stylesheet_link_tag    "application", media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    #display
      = yield

app/views/pages/index.html.slim
.alert.alert-dismissable.alert-success
  .button.close type="button" data-dismiss="alert"×
  strong Well done!
  span  You have successfully started
  a.alert-link href="javascript:void(0)"  a new Bluesquare app

.panel.panel-bluesquare
  .panel-heading
    h1 Bluesquare presents
  .panel-body
    h1= t('hello')
    h4
      | Don't forget to
      .btn.btn-bluesquare Boom
    h2 h2
    h3 h3
    h4 h4
    h5 h5
    h6 h6
    a link

.panel.panel-info.shadow-z-2
  .panel-heading
    h2 Material reference
  .panel-body
    =link_to('Material Boostrap Demos','http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html', target: '_blank', class: "btn btn-info btn-raised")
    p

      button.btn.btn-fab.btn-raised.btn-primary
        i.mdi-image-edit
        .ripple-wrapper

      button.btn.btn-fab.btn-raised.btn-danger
        i.mdi-action-delete
        .ripple-wrapper

      button.btn.btn-fab.btn-raised.btn-success
        i.mdi-action-done
        .ripple-wrapper

      button.btn.btn-fab.btn-raised.btn-info
        i.mdi-navigation-arrow-forward
        .ripple-wrapper

      button.btn.btn-fab.btn-raised.btn-warning
        i.mdi-content-clear
        .ripple-wrapper

      button.btn.btn-fab.btn-raised.btn-fab-mini.btn-default
        i.mdi-content-add
        .ripple-wrapper

  i.icon.icon-material-favorite

app/views/shared/_navbar.html.slim
nav.navbar.navbar-fixed-top role="navigation"
  div.navbar-container
    div.navbar-header
      = link_to :back do
        i.mdi-hardware-keyboard-arrow-left